---
pacman_installed_packages:
  - cowsay
  - neofetch
  - git
  - fish
  - vim
  - ansible-lint
  - steam
  - ttf-liberation
  - wqy-zenhei
  - ttf-roboto
  - noto-fonts
  - noto-fonts-cjk
  - adobe-source-han-sans-cn-fonts
  - adobe-source-han-serif-cn-fonts
  - ttf-dejavu
  - lib32-mesa
  - vulkan-radeon
  - lib32-vulkan-radeon
  - vulkan-icd-loader
  - lib32-vulkan-icd-loader
  - net-tools
  - vagrant
  - virtualbox-host-modules-arch
  - virtualbox
  - tmux
  - x11vnc
  - neovim
  - docker
  - docker-compose
  - bash-completion
  - reflector

pacman_uninstalled_packages: []

pacman_upgrade_all_packages: true

docker_users:
  - kchou

docker_daemon_options:
  storage-driver: "btrfs"
